# Generated by Django 4.2.11 on 2024-05-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPoemHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poems',
            name='title',
            field=models.CharField(default='bro', max_length=100),
            preserve_default=False,
        ),
    ]
